// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MySql.EntityFrameworkCore.Extensions;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(RishtanataDbContext))]
    [Migration("20260830061853_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BrideFormSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("MarriageApplicationFormId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("MarriageApplicationFormId")
                        .IsUnique();

                    b.ToTable("BrideFormSection");
                });

            modelBuilder.Entity("Domain.Entities.AmirApprovalSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ApprovedDateOfNikah")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("MarriageApplicationFormId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("SignatureDate")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("MarriageApplicationFormId")
                        .IsUnique();

                    b.ToTable("AmirApprovalSection");
                });

            modelBuilder.Entity("Domain.Entities.AqeeqahCertificate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("AnimalCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("AqeeqahDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("AqeeqahLocation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CertificateFilePath")
                        .HasColumnType("longtext");

                    b.Property<string>("ChildName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FatherName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("IssuedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("JamaatId")
                        .HasColumnType("char(36)");

                    b.Property<string>("JamaatName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("MotherName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OfficiatingMissionary")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PlaceOfBirth")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("AqeeqahCertificates");
                });

            modelBuilder.Entity("Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ChangeDetails")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("RecordId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.HasIndex("EntityName", "RecordId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Domain.Entities.BrideGuardian", b =>
                {
                    b.Property<Guid>("BrideGuardianId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("GuardianAddress")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("GuardianName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("GuardianRelationToBride")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("GuardianSignatureDate")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("GuardianTel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("MarriageApplicationId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("BrideGuardianId");

                    b.ToTable("BrideGuardian");
                });

            modelBuilder.Entity("Domain.Entities.BridegroomFormSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("BridegroomBloodGroup")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("BridegroomDateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("BridegroomDowerAmountPaidInCash")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("BridegroomDowerAmountToBePaid")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("BridegroomGenotype")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("BridegroomMembershipNo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("BridegroomName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("BridegroomResidentOf")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("BridegroomSignatureTel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<bool>("FormerWifeIsDead")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("FormerWifeIsPresent")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("FormerWifeObtainedKhula")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("HasDivorcedFormerWife")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsFirstNikah")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsSecondThirdOrFourthNikah")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("MarriageApplicationFormId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("MarriageApplicationFormId")
                        .IsUnique();

                    b.ToTable("BrideGrooms", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Certificate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("BrideFatherName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("BrideName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("BrideResidentOf")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("BridegroomFatherName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("BridegroomName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("BridegroomResidentOf")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CertificateFilePath")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("DowryAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("FormApplicationId")
                        .HasColumnType("char(36)")
                        .HasColumnName("MarriageApplicationId");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("IssuedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("NikahDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("FormApplicationId")
                        .IsUnique();

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("Domain.Entities.FormApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CertificateId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("MarriageApplicationFormId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("FormApplications");
                });

            modelBuilder.Entity("Domain.Entities.GuardianOrWakeelSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ActingFor")
                        .HasColumnType("longtext");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("JamaatMemberId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("MarriageApplicationFormId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PartyType")
                        .HasColumnType("int");

                    b.Property<string>("RelationToBride")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Signature")
                        .HasColumnType("longtext");

                    b.Property<string>("Tel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("JamaatMemberId");

                    b.HasIndex("MarriageApplicationFormId")
                        .IsUnique();

                    b.ToTable("GuardianOrWakeelSection");
                });

            modelBuilder.Entity("Domain.Entities.ImamVerificationSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AddressJamaat")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("MarriageApplicationFormId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SignatureDate")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("MarriageApplicationFormId")
                        .IsUnique();

                    b.ToTable("ImamVerificationSection");
                });

            modelBuilder.Entity("Domain.Entities.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("MarriageApplicationId")
                        .HasColumnType("char(36)");

                    b.Property<string>("MarriageReferenceNumber")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("RecipientJamaatMemberId")
                        .HasColumnType("char(36)");

                    b.Property<string>("RecipientMembershipNo")
                        .HasColumnType("longtext");

                    b.Property<int>("TargetType")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Used")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Invitations");
                });

            modelBuilder.Entity("Domain.Entities.JamaatMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("AuxillaryBodyName")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("BrideGuardianId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ChandaNo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CircuitName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsSystemDefault")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("JamaatName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MaidenName")
                        .HasColumnType("longtext");

                    b.Property<string>("MaritalStatus")
                        .HasColumnType("longtext");

                    b.Property<string>("MiddleName")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("Nationality")
                        .HasColumnType("longtext");

                    b.Property<string>("NewRole")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NextOfKinAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("NextOfKinName")
                        .HasColumnType("longtext");

                    b.Property<string>("NextOfKinPhoneNo")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNo")
                        .HasColumnType("longtext");

                    b.Property<string>("ResetToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ResetTokenExpiry")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.Property<string>("WasiyatNo")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("BrideGuardianId");

                    b.ToTable("JamaatMembers");
                });

            modelBuilder.Entity("Domain.Entities.JamaatMemberRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("AssignedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("JamaatMemberId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("JamaatMemberId", "RoleId")
                        .IsUnique();

                    b.ToTable("JamaatMemberRoles");
                });

            modelBuilder.Entity("Domain.Entities.JamaatPresidentVerificationSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("MarriageApplicationFormId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SignatureDate")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("MarriageApplicationFormId")
                        .IsUnique();

                    b.ToTable("JamaatPresidentVerificationSection");
                });

            modelBuilder.Entity("Domain.Entities.MarriageApplicationForm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int?>("ApplicationStage")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ApprovedDateOfNikah")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("BrideBloodGroup")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("BrideDateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("BrideDowerAmountReceivedInCash")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BrideFatherName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("BrideGenotype")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("BrideMaritalStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("BrideMembershipNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("BrideName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("BrideProposedDowerAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BrideResidentOf")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("BrideSignatureTel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("BridegroomBloodGroup")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("BridegroomDateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("BridegroomDowerAmountPaidInCash")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BridegroomDowerAmountToBePaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BridegroomFatherName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("BridegroomGenotype")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("BridegroomMembershipNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("BridegroomName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("BridegroomResidentOf")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("BridegroomSignatureTel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<int>("FormStage")
                        .HasColumnType("int");

                    b.Property<bool>("FormerWifeIsDead")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("FormerWifeIsPresent")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("FormerWifeObtainedKhula")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("GuardianAddress")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("GuardianName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("GuardianRelationToBride")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("GuardianSignatureDate")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("GuardianTel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<bool>("HasDivorcedFormerWife")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsFirstNikah")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsSecondThirdOrFourthNikah")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("JamaatPresidentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("JamaatPresidentSignatureDate")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("MarriageApplicationId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("NationalAmirOrMissionarySignatureDate")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NationalRishtanataSecretaryName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NationalRishtanataSecretarySignatureDate")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("OfficiatingImamAddressJamaat")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("OfficiatingImamName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("OfficiatingImamSignatureDate")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("ProposedNikahDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("RepresentativeActingFor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("RepresentativeAddress")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("RepresentativeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("RepresentativeSignatureDate")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("WitnessOneAddress")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("WitnessOneName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("WitnessOneSignatureDate")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("WitnessOneTel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("WitnessTwoAddress")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("WitnessTwoName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("WitnessTwoSignatureDate")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("WitnessTwoTel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("MarriageApplicationId")
                        .IsUnique();

                    b.ToTable("MarriageApplicationForms");
                });

            modelBuilder.Entity("Domain.Entities.MarriageFormRejection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("MarriageApplicationFormId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("RejectedAtStage")
                        .HasColumnType("int");

                    b.Property<int>("RevertedToStage")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MarriageApplicationFormId");

                    b.ToTable("MarriageFormRejections");
                });

            modelBuilder.Entity("Domain.Entities.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("MarriageApplicationId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ReviewedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ReviewerId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("MarriageApplicationId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Domain.Entities.RishtanataRecommendationSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("MarriageApplicationFormId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("SignatureDate")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("WakeelDeclaration")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("WakeelName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("MarriageApplicationFormId")
                        .IsUnique();

                    b.ToTable("RishtanataRecommendationSection");
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int>("HierarchyLevel")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("JamaatRoles");
                });

            modelBuilder.Entity("WitnessSignatureSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("MarriageApplicationFormId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Signature")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("SignatureDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Tel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("WitnessContext")
                        .HasColumnType("int");

                    b.Property<int>("WitnessNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MarriageApplicationFormId");

                    b.ToTable("WitnessSignatureSection");
                });

            modelBuilder.Entity("BrideFormSection", b =>
                {
                    b.HasOne("Domain.Entities.MarriageApplicationForm", "MarriageApplicationForm")
                        .WithOne("BrideSection")
                        .HasForeignKey("BrideFormSection", "MarriageApplicationFormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarriageApplicationForm");
                });

            modelBuilder.Entity("Domain.Entities.AmirApprovalSection", b =>
                {
                    b.HasOne("Domain.Entities.MarriageApplicationForm", "MarriageApplicationForm")
                        .WithOne("AmirApproval")
                        .HasForeignKey("Domain.Entities.AmirApprovalSection", "MarriageApplicationFormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarriageApplicationForm");
                });

            modelBuilder.Entity("Domain.Entities.BridegroomFormSection", b =>
                {
                    b.HasOne("Domain.Entities.MarriageApplicationForm", "MarriageApplicationForm")
                        .WithOne("BridegroomSection")
                        .HasForeignKey("Domain.Entities.BridegroomFormSection", "MarriageApplicationFormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarriageApplicationForm");
                });

            modelBuilder.Entity("Domain.Entities.Certificate", b =>
                {
                    b.HasOne("Domain.Entities.FormApplication", "FormApplication")
                        .WithOne("Certificate")
                        .HasForeignKey("Domain.Entities.Certificate", "FormApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FormApplication");
                });

            modelBuilder.Entity("Domain.Entities.GuardianOrWakeelSection", b =>
                {
                    b.HasOne("Domain.Entities.JamaatMember", "JamaatMember")
                        .WithMany()
                        .HasForeignKey("JamaatMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.MarriageApplicationForm", "MarriageApplicationForm")
                        .WithOne("GuardianOrWakeelSection")
                        .HasForeignKey("Domain.Entities.GuardianOrWakeelSection", "MarriageApplicationFormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JamaatMember");

                    b.Navigation("MarriageApplicationForm");
                });

            modelBuilder.Entity("Domain.Entities.ImamVerificationSection", b =>
                {
                    b.HasOne("Domain.Entities.MarriageApplicationForm", "MarriageApplicationForm")
                        .WithOne("ImamVerification")
                        .HasForeignKey("Domain.Entities.ImamVerificationSection", "MarriageApplicationFormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarriageApplicationForm");
                });

            modelBuilder.Entity("Domain.Entities.JamaatMember", b =>
                {
                    b.HasOne("Domain.Entities.BrideGuardian", "BrideGuardian")
                        .WithMany("Brides")
                        .HasForeignKey("BrideGuardianId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BrideGuardian");
                });

            modelBuilder.Entity("Domain.Entities.JamaatMemberRole", b =>
                {
                    b.HasOne("Domain.Entities.JamaatMember", "JamaatMember")
                        .WithMany("MemberRoles")
                        .HasForeignKey("JamaatMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Role", "Role")
                        .WithMany("MemberRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("JamaatMember");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Entities.JamaatPresidentVerificationSection", b =>
                {
                    b.HasOne("Domain.Entities.MarriageApplicationForm", "MarriageApplicationForm")
                        .WithOne("JamaatPresidentVerification")
                        .HasForeignKey("Domain.Entities.JamaatPresidentVerificationSection", "MarriageApplicationFormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarriageApplicationForm");
                });

            modelBuilder.Entity("Domain.Entities.MarriageApplicationForm", b =>
                {
                    b.HasOne("Domain.Entities.FormApplication", "MarriageApplication")
                        .WithOne("MarriageApplicationForm")
                        .HasForeignKey("Domain.Entities.MarriageApplicationForm", "MarriageApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarriageApplication");
                });

            modelBuilder.Entity("Domain.Entities.MarriageFormRejection", b =>
                {
                    b.HasOne("Domain.Entities.MarriageApplicationForm", "MarriageApplicationForm")
                        .WithMany("Rejections")
                        .HasForeignKey("MarriageApplicationFormId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MarriageApplicationForm");
                });

            modelBuilder.Entity("Domain.Entities.Review", b =>
                {
                    b.HasOne("Domain.Entities.FormApplication", "MarriageApplication")
                        .WithMany()
                        .HasForeignKey("MarriageApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MarriageApplication");
                });

            modelBuilder.Entity("Domain.Entities.RishtanataRecommendationSection", b =>
                {
                    b.HasOne("Domain.Entities.MarriageApplicationForm", "MarriageApplicationForm")
                        .WithOne("RishtanataRecommendation")
                        .HasForeignKey("Domain.Entities.RishtanataRecommendationSection", "MarriageApplicationFormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarriageApplicationForm");
                });

            modelBuilder.Entity("WitnessSignatureSection", b =>
                {
                    b.HasOne("Domain.Entities.MarriageApplicationForm", "MarriageApplicationForm")
                        .WithMany("WitnessSignatures")
                        .HasForeignKey("MarriageApplicationFormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarriageApplicationForm");
                });

            modelBuilder.Entity("Domain.Entities.BrideGuardian", b =>
                {
                    b.Navigation("Brides");
                });

            modelBuilder.Entity("Domain.Entities.FormApplication", b =>
                {
                    b.Navigation("Certificate")
                        .IsRequired();

                    b.Navigation("MarriageApplicationForm")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.JamaatMember", b =>
                {
                    b.Navigation("MemberRoles");
                });

            modelBuilder.Entity("Domain.Entities.MarriageApplicationForm", b =>
                {
                    b.Navigation("AmirApproval");

                    b.Navigation("BrideSection");

                    b.Navigation("BridegroomSection");

                    b.Navigation("GuardianOrWakeelSection");

                    b.Navigation("ImamVerification");

                    b.Navigation("JamaatPresidentVerification");

                    b.Navigation("Rejections");

                    b.Navigation("RishtanataRecommendation");

                    b.Navigation("WitnessSignatures");
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Navigation("MemberRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
